tasks:
# Some utilities
  - name: utils 
    before: |
      sudo apt-get install tree 
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
      AWS_ACCESS_KEY_ID: AKIA5FTZDJZPIBQIRGK4
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: ap-south-1
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
