#! /usr/bin/env bash
echo "== delete bucket"

# Checks if there are any argument for our script
if [ -z "$1" ]; then
    echo "No bucket name provided, eg. ./bucket my-bucket2412"
    exit 1
fi

# runs the command to create bucket using argument and s3api
# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html for location constraints
aws s3api delete-bucket \
--bucket $1 \

