#! /usr/bin/env bash
echo "== list object"

# Checks if there is a bucket-name
if [ -z "$1" ]; then
    echo "No bucket name provided, eg. ./bucket my-bucket2412"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query 