#! /usr/bin/env bash
echo "== sync"

set -e
# Checks if there are any bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided, eg. ./bucket my-bucket2412"
    exit 1
fi

# Checks if there are any file prefix name
if [ -z "$2" ]; then
    echo "No File prefix name provided, eg. ./bucket my-bucket2412/images"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

OUTPUT_DIR="tmp/s3-bash-scripts"

if [ -e $OUTPUT_DIR ]; then
    rm -r $OUTPUT_DIR
fi


mkdir -p $OUTPUT_DIR

NUM_FILES=$(( RANDOM % 6 + 5))

for ((i = 1; i <= $NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # Generate random data and write it into files
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$(( RANDOM % 1024 + 1)) 2>/dev/null

done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files